import type { ArmorDef, ArmorSlot } from "../core/types";

export const ARMOR: ArmorDef[] = [
  {
    id: "cloth-wrap",
    slot: "helmet",
    name: "Cloth Wrap",
    protection: 0.04,
    weight: 0.2,
    durability: 40,
    mobility: 1.02,
    color: "#e8d7b5",
    trim: "#6b4423",
    unlockLevel: 1,
    cost: 0,
    description: "Barely a hat. Keeps sweat out of your eyes.",
  },
  {
    id: "ridge-helm",
    slot: "helmet",
    name: "Ridge Helm",
    protection: 0.22,
    weight: 1.4,
    durability: 90,
    mobility: 0.94,
    color: "#8aa0b3",
    trim: "#c4843a",
    unlockLevel: 3,
    cost: 160,
    description: "Bronze-ridge helmet. Strong vs head shots.",
  },
  {
    id: "crest-helm",
    slot: "helmet",
    name: "Crest Helm",
    protection: 0.3,
    weight: 1.8,
    durability: 110,
    mobility: 0.9,
    color: "#c5d0d8",
    trim: "#8b1e2d",
    unlockLevel: 7,
    cost: 320,
    description: "Full crest. Intimidating and heavy.",
  },
  {
    id: "leather-harness",
    slot: "chest",
    name: "Leather Harness",
    protection: 0.1,
    weight: 1.0,
    durability: 60,
    mobility: 1.04,
    color: "#6b4423",
    trim: "#c4a574",
    unlockLevel: 1,
    cost: 0,
    description: "Light straps. Fast, fragile.",
  },
  {
    id: "scale-mail",
    slot: "chest",
    name: "Scale Mail",
    protection: 0.28,
    weight: 2.6,
    durability: 120,
    mobility: 0.9,
    color: "#8aa0b3",
    trim: "#4a5560",
    unlockLevel: 4,
    cost: 240,
    description: "Overlapping scales. Solid torso protection.",
  },
  {
    id: "muscle-cuirass",
    slot: "chest",
    name: "Muscle Cuirass",
    protection: 0.38,
    weight: 3.4,
    durability: 150,
    mobility: 0.82,
    color: "#c4843a",
    trim: "#e8c547",
    unlockLevel: 8,
    cost: 420,
    description: "Ceremonial bronze plate. Slow and stubborn.",
  },
  {
    id: "leather-pads",
    slot: "shoulder",
    name: "Leather Pads",
    protection: 0.08,
    weight: 0.6,
    durability: 50,
    mobility: 1.0,
    color: "#6b4423",
    trim: "#3a2a1c",
    unlockLevel: 2,
    cost: 80,
    description: "Soft pauldrons for glancing blows.",
  },
  {
    id: "bronze-pauldrons",
    slot: "shoulder",
    name: "Bronze Pauldrons",
    protection: 0.18,
    weight: 1.6,
    durability: 95,
    mobility: 0.92,
    color: "#c4843a",
    trim: "#8aa0b3",
    unlockLevel: 5,
    cost: 200,
    description: "Heavy shoulders. Adds mass to charges.",
  },
  {
    id: "wrap-gloves",
    slot: "gloves",
    name: "Wrap Gloves",
    protection: 0.05,
    weight: 0.2,
    durability: 40,
    mobility: 1.03,
    color: "#c4a574",
    trim: "#6b4423",
    unlockLevel: 1,
    cost: 30,
    description: "Keeps grip on sweaty hilts.",
  },
  {
    id: "plated-gauntlets",
    slot: "gloves",
    name: "Plated Gauntlets",
    protection: 0.16,
    weight: 0.9,
    durability: 90,
    mobility: 0.95,
    color: "#8aa0b3",
    trim: "#c4843a",
    unlockLevel: 6,
    cost: 180,
    description: "Harder to disarm. Slightly slower swings.",
  },
  {
    id: "wrap-legs",
    slot: "legs",
    name: "Linen Greaves",
    protection: 0.08,
    weight: 0.5,
    durability: 50,
    mobility: 1.02,
    color: "#e8d7b5",
    trim: "#6b4423",
    unlockLevel: 1,
    cost: 0,
    description: "Light wraps. Easy footwork.",
  },
  {
    id: "bronze-greaves",
    slot: "legs",
    name: "Bronze Greaves",
    protection: 0.22,
    weight: 1.8,
    durability: 100,
    mobility: 0.9,
    color: "#c4843a",
    trim: "#4a5560",
    unlockLevel: 5,
    cost: 210,
    description: "Protects against low cuts and stumbles.",
  },
  {
    id: "sandals",
    slot: "boots",
    name: "Arena Sandals",
    protection: 0.04,
    weight: 0.3,
    durability: 35,
    mobility: 1.05,
    color: "#6b4423",
    trim: "#c4a574",
    unlockLevel: 1,
    cost: 0,
    description: "Fast on sand. Poor against traps.",
  },
  {
    id: "iron-boots",
    slot: "boots",
    name: "Iron Boots",
    protection: 0.18,
    weight: 1.5,
    durability: 110,
    mobility: 0.88,
    color: "#4a5560",
    trim: "#8aa0b3",
    unlockLevel: 6,
    cost: 190,
    description: "Planted stance. Harder to knock down.",
  },
];

export function armorById(id: string | null) {
  if (!id) return null;
  return ARMOR.find((a) => a.id === id) ?? null;
}

export function armorForSlot(slot: ArmorSlot) {
  return ARMOR.filter((a) => a.slot === slot);
}
