import type { WeaponDef } from "../core/types";

export const WEAPONS: WeaponDef[] = [
  {
    id: "gladius",
    name: "Gladius",
    category: "shortsword",
    damage: 14,
    knockback: 0.9,
    attackSpeed: 1.35,
    reach: 42,
    weight: 1.1,
    staminaCost: 10,
    throwDamage: 10,
    twoHanded: false,
    isRanged: false,
    isShield: false,
    width: 8,
    length: 42,
    blade: "#c5d0d8",
    haft: "#6b4423",
    swingArc: 2.2,
    chargeMult: 1.7,
    unlockLevel: 1,
    cost: 0,
    description: "Fast legion short blade. Reliable cuts and quick recovery.",
  },
  {
    id: "spatha",
    name: "Spatha",
    category: "longsword",
    damage: 20,
    knockback: 1.15,
    attackSpeed: 0.95,
    reach: 62,
    weight: 1.7,
    staminaCost: 16,
    throwDamage: 12,
    twoHanded: false,
    isRanged: false,
    isShield: false,
    width: 6,
    length: 62,
    blade: "#d8e2ea",
    haft: "#3b2418",
    swingArc: 2.4,
    chargeMult: 1.85,
    unlockLevel: 3,
    cost: 180,
    description: "Long cavalry sword. Heavy arcs and strong knockback.",
  },
  {
    id: "hasta",
    name: "Hasta",
    category: "spear",
    damage: 16,
    knockback: 1.05,
    attackSpeed: 1.05,
    reach: 86,
    weight: 1.5,
    staminaCost: 13,
    throwDamage: 18,
    twoHanded: true,
    isRanged: false,
    isShield: false,
    width: 4,
    length: 86,
    blade: "#e8eef2",
    haft: "#6b4423",
    swingArc: 1.2,
    chargeMult: 1.6,
    unlockLevel: 2,
    cost: 120,
    description: "Long reach thrusts. Excellent for keeping foes away.",
  },
  {
    id: "labrys",
    name: "Labrys",
    category: "axe",
    damage: 24,
    knockback: 1.35,
    attackSpeed: 0.82,
    reach: 48,
    weight: 2.1,
    staminaCost: 20,
    throwDamage: 16,
    twoHanded: false,
    isRanged: false,
    isShield: false,
    width: 16,
    length: 46,
    blade: "#9aa7b2",
    haft: "#5c3824",
    swingArc: 2.6,
    chargeMult: 2.1,
    unlockLevel: 4,
    cost: 240,
    description: "Crescent axe. Brutal impact, slow recovery.",
  },
  {
    id: "star-mace",
    name: "Star Mace",
    category: "mace",
    damage: 22,
    knockback: 1.5,
    attackSpeed: 0.88,
    reach: 44,
    weight: 2.4,
    staminaCost: 18,
    throwDamage: 14,
    twoHanded: false,
    isRanged: false,
    isShield: false,
    width: 14,
    length: 42,
    blade: "#8aa0b3",
    haft: "#3a2a1c",
    swingArc: 2.1,
    chargeMult: 1.9,
    unlockLevel: 5,
    cost: 260,
    description: "Flanged head that staggers through light armor.",
  },
  {
    id: "pugio",
    name: "Pugio",
    category: "dagger",
    damage: 9,
    knockback: 0.45,
    attackSpeed: 1.85,
    reach: 26,
    weight: 0.55,
    staminaCost: 6,
    throwDamage: 12,
    twoHanded: false,
    isRanged: false,
    isShield: false,
    width: 4,
    length: 26,
    blade: "#d0d8e0",
    haft: "#6b1d2a",
    swingArc: 1.8,
    chargeMult: 1.4,
    unlockLevel: 1,
    cost: 40,
    description: "Lightning stabs and easy throws. Low reach.",
  },
  {
    id: "forge-hammer",
    name: "Forge Hammer",
    category: "hammer",
    damage: 28,
    knockback: 1.85,
    attackSpeed: 0.68,
    reach: 40,
    weight: 3.2,
    staminaCost: 24,
    throwDamage: 20,
    twoHanded: true,
    isRanged: false,
    isShield: false,
    width: 16,
    length: 40,
    blade: "#6b7280",
    haft: "#6b4423",
    swingArc: 2.0,
    chargeMult: 2.3,
    unlockLevel: 7,
    cost: 340,
    description: "Massive weight. Sends bodies flying on sweet-spot hits.",
  },
  {
    id: "poleaxe",
    name: "Poleaxe",
    category: "halberd",
    damage: 23,
    knockback: 1.4,
    attackSpeed: 0.78,
    reach: 92,
    weight: 2.8,
    staminaCost: 22,
    throwDamage: 14,
    twoHanded: true,
    isRanged: false,
    isShield: false,
    width: 10,
    length: 92,
    blade: "#b8c4ce",
    haft: "#3b2418",
    swingArc: 1.7,
    chargeMult: 1.95,
    unlockLevel: 8,
    cost: 400,
    description: "Hook, chop, and keep distance. Demands stamina.",
  },
  {
    id: "recurve",
    name: "Recurve Bow",
    category: "bow",
    damage: 15,
    knockback: 0.7,
    attackSpeed: 0.9,
    reach: 160,
    weight: 0.9,
    staminaCost: 12,
    throwDamage: 8,
    twoHanded: true,
    isRanged: true,
    isShield: false,
    width: 6,
    length: 36,
    blade: "#6b4423",
    haft: "#c4a574",
    swingArc: 0.4,
    chargeMult: 2.0,
    unlockLevel: 6,
    cost: 300,
    description: "Charge shots into physical arrows. Weak in a clinch.",
  },
  {
    id: "buckler",
    name: "Buckler",
    category: "shield",
    damage: 8,
    knockback: 1.1,
    attackSpeed: 1.2,
    reach: 18,
    weight: 1.2,
    staminaCost: 8,
    throwDamage: 10,
    twoHanded: false,
    isRanged: false,
    isShield: true,
    width: 22,
    length: 22,
    blade: "#c4843a",
    haft: "#4a5560",
    swingArc: 1.1,
    chargeMult: 1.3,
    unlockLevel: 1,
    cost: 0,
    description: "Small round shield. Fast bash, modest cover.",
  },
  {
    id: "scutum",
    name: "Tower Scutum",
    category: "shield",
    damage: 12,
    knockback: 1.4,
    attackSpeed: 0.85,
    reach: 24,
    weight: 2.6,
    staminaCost: 12,
    throwDamage: 11,
    twoHanded: false,
    isRanged: false,
    isShield: true,
    width: 28,
    length: 42,
    blade: "#8b1e2d",
    haft: "#c4843a",
    swingArc: 0.9,
    chargeMult: 1.5,
    unlockLevel: 4,
    cost: 220,
    description: "Heavy cover. Slows movement, shrugs off arrows.",
  },
];

export function weaponById(id: string) {
  return WEAPONS.find((w) => w.id === id) ?? WEAPONS[0];
}

export function unlockedWeapons(level: number, extra: string[]) {
  return WEAPONS.filter((w) => w.unlockLevel <= level || extra.includes(w.id));
}
